detectorSet: [c_0, d_0, e_0, f_0, g_0, h_0, i_0, j_0, k_0, l_0, m_0, n_0, o_0, p_0, q_0]
DIM: 7
vaaFun: "expansionFuncs/October 15, 2023/MKP_7D_FixedFixed.txt"
singleDetect: False
numOfPhases: 14
output: "MKP_7D_FixedFixed"


